---

- import_tasks: check.yml

- import_tasks: backup.yml
  when: vipre_backup and (vipre_backup_remote or vipre_backup_local)

- import_tasks: uninstall.yml
  when: vipre_uninstall

- import_tasks: check.yml
  when: vipre_uninstall

- import_tasks: install.yml
  when: vipre_install

- import_tasks: check.yml
  when: vipre_install

- import_tasks: restore.yml
  when: vipre_restore and (vipre_restore_remote or vipre_restore_local or vipre_restore_site_guid or vipre_restore_reg_code)

- import_tasks: check.yml
  when: vipre_restore
